"""add_area_and_salary_to_users

Revision ID: 74d3f89af973
Revises: b168eef0722e
Create Date: 2025-12-16 07:01:35.059135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d3f89af973'
down_revision: Union[str, Sequence[str], None] = 'b168eef0722e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('salary', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salary')
    op.drop_column('users', 'area')
    # ### end Alembic commands ###
